package com.database.model;
// Generated 20-dic-2017 10:10:06 by Hibernate Tools 5.2.5.Final

/**
 * EnvasesHasVinoId generated by hbm2java
 */
public class EnvasesHasVinoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int envasesIdEnvases;
	private int vinoIdVino;
	private int vinoTiposVinoIdTiposVino;

	public EnvasesHasVinoId() {
	}

	public EnvasesHasVinoId(int envasesIdEnvases, int vinoIdVino, int vinoTiposVinoIdTiposVino) {
		this.envasesIdEnvases = envasesIdEnvases;
		this.vinoIdVino = vinoIdVino;
		this.vinoTiposVinoIdTiposVino = vinoTiposVinoIdTiposVino;
	}

	public int getEnvasesIdEnvases() {
		return this.envasesIdEnvases;
	}

	public void setEnvasesIdEnvases(int envasesIdEnvases) {
		this.envasesIdEnvases = envasesIdEnvases;
	}

	public int getVinoIdVino() {
		return this.vinoIdVino;
	}

	public void setVinoIdVino(int vinoIdVino) {
		this.vinoIdVino = vinoIdVino;
	}

	public int getVinoTiposVinoIdTiposVino() {
		return this.vinoTiposVinoIdTiposVino;
	}

	public void setVinoTiposVinoIdTiposVino(int vinoTiposVinoIdTiposVino) {
		this.vinoTiposVinoIdTiposVino = vinoTiposVinoIdTiposVino;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnvasesHasVinoId))
			return false;
		EnvasesHasVinoId castOther = (EnvasesHasVinoId) other;

		return (this.getEnvasesIdEnvases() == castOther.getEnvasesIdEnvases())
				&& (this.getVinoIdVino() == castOther.getVinoIdVino())
				&& (this.getVinoTiposVinoIdTiposVino() == castOther.getVinoTiposVinoIdTiposVino());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnvasesIdEnvases();
		result = 37 * result + this.getVinoIdVino();
		result = 37 * result + this.getVinoTiposVinoIdTiposVino();
		return result;
	}

}
