package com.database.model;
// Generated 20-dic-2017 10:10:06 by Hibernate Tools 5.2.5.Final

/**
 * EnvasesHasVino generated by hbm2java
 */
public class EnvasesHasVino implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EnvasesHasVinoId id;

	public EnvasesHasVino() {
	}

	public EnvasesHasVino(EnvasesHasVinoId id) {
		this.id = id;
	}

	public EnvasesHasVinoId getId() {
		return this.id;
	}

	public void setId(EnvasesHasVinoId id) {
		this.id = id;
	}

}
