package com.database.model;
// Generated 20-dic-2017 10:10:06 by Hibernate Tools 5.2.5.Final

/**
 * Envases generated by hbm2java
 */
public class Envases implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEnvases;
	private TiposEmbases tiposEmbases;
	private short peso;

	public Envases() {
	}

	public Envases(TiposEmbases tiposEmbases, short peso) {
		this.tiposEmbases = tiposEmbases;
		this.peso = peso;
	}

	public Integer getIdEnvases() {
		return this.idEnvases;
	}

	public void setIdEnvases(Integer idEnvases) {
		this.idEnvases = idEnvases;
	}

	public TiposEmbases getTiposEmbases() {
		return this.tiposEmbases;
	}

	public void setTiposEmbases(TiposEmbases tiposEmbases) {
		this.tiposEmbases = tiposEmbases;
	}

	public short getPeso() {
		return this.peso;
	}

	public void setPeso(short peso) {
		this.peso = peso;
	}

}
