package com.database.model;
// Generated 20-dic-2017 10:10:06 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TiposEmbases generated by hbm2java
 */
public class TiposEmbases implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTiposEmbases;
	private String descripcion;
	private long pesoUnidad;
	private Set<Envases> envases = new HashSet<Envases>(0);

	public TiposEmbases() {
	}

	public TiposEmbases(String descripcion, long pesoUnidad) {
		this.descripcion = descripcion;
		this.pesoUnidad = pesoUnidad;
	}

	public TiposEmbases(String descripcion, long pesoUnidad, Set<Envases> envaseses) {
		this.descripcion = descripcion;
		this.pesoUnidad = pesoUnidad;
		this.envases = envaseses;
	}

	public int getIdTiposEmbases() {
		return this.idTiposEmbases;
	}

	public void setIdTiposEmbases(int idTiposEmbases) {
		this.idTiposEmbases = idTiposEmbases;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public long getPesoUnidad() {
		return this.pesoUnidad;
	}

	public void setPesoUnidad(long pesoUnidad) {
		this.pesoUnidad = pesoUnidad;
	}

	public Set<Envases> getEnvases() {
		return envases;
	}

	public void setEnvases(Set<Envases> envases) {
		this.envases = envases;
	}
}
