package com.database.model;
// Generated 20-dic-2017 10:10:06 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Vino generated by hbm2java
 */
public class Vino implements java.io.Serializable {

	private Integer idVino;
	private TiposVino tiposVino;
	private String descripcion;
	private Date anio;

	public Vino() {
	}

	public Vino(TiposVino tiposVino, String descripcion) {
		this.tiposVino = tiposVino;
		this.descripcion = descripcion;
	}

	public Vino(TiposVino tiposVino, String descripcion, Date anio) {
		this.tiposVino = tiposVino;
		this.descripcion = descripcion;
		this.anio = anio;
	}

	public Integer getIdVino() {
		return this.idVino;
	}

	public void setIdVino(Integer idVino) {
		this.idVino = idVino;
	}

	public TiposVino getTiposVino() {
		return this.tiposVino;
	}

	public void setTiposVino(TiposVino tiposVino) {
		this.tiposVino = tiposVino;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

}
